[mgr]
show_hidden = true

[tasks]
# Avoid quit warnings from unfinished video thumbnail preload tasks.
suppress_preload = true

[open]
prepend_rules = [
  { url = "*.html", use = "open" },
  { url = "*.htm", use = "open" },
]
